"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from collections.abc import Callable  # noqa: F401 # pylint: disable=W0611
from datetime import datetime  # noqa: F401 # pylint: disable=W0611
from enum import Enum  # noqa: F401 # pylint: disable=W0611
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)

from reconcile.gql_definitions.fragments.vault_secret import VaultSecret


class ConfiguredBaseModel(BaseModel):
    class Config:
        smart_union=True
        extra=Extra.forbid


class AWSTerraformStateIntegrationsV1(ConfiguredBaseModel):
    key: str = Field(..., alias="key")
    integration: str = Field(..., alias="integration")


class TerraformStateAWSV1(ConfiguredBaseModel):
    provider: str = Field(..., alias="provider")
    bucket: str = Field(..., alias="bucket")
    region: str = Field(..., alias="region")
    integrations: list[AWSTerraformStateIntegrationsV1] = Field(..., alias="integrations")


class DeletionApprovalV1(ConfiguredBaseModel):
    q_type: str = Field(..., alias="type")
    name: str = Field(..., alias="name")
    expiration: str = Field(..., alias="expiration")


class DisableClusterAutomationsV1(ConfiguredBaseModel):
    integrations: Optional[list[str]] = Field(..., alias="integrations")


class AWSAccountTerraform(ConfiguredBaseModel):
    path: str = Field(..., alias="path")
    name: str = Field(..., alias="name")
    uid: str = Field(..., alias="uid")
    terraform_username: Optional[str] = Field(..., alias="terraformUsername")
    terraform_state: Optional[TerraformStateAWSV1] = Field(..., alias="terraformState")
    resources_default_region: str = Field(..., alias="resourcesDefaultRegion")
    supported_deployment_regions: Optional[list[str]] = Field(..., alias="supportedDeploymentRegions")
    provider_version: str = Field(..., alias="providerVersion")
    automation_token: VaultSecret = Field(..., alias="automationToken")
    garbage_collection: Optional[bool] = Field(..., alias="garbageCollection")
    enable_deletion: Optional[bool] = Field(..., alias="enableDeletion")
    deletion_approvals: Optional[list[DeletionApprovalV1]] = Field(..., alias="deletionApprovals")
    disable: Optional[DisableClusterAutomationsV1] = Field(..., alias="disable")
    delete_keys: Optional[list[str]] = Field(..., alias="deleteKeys")
    premium_support: bool = Field(..., alias="premiumSupport")
    partition: Optional[str] = Field(..., alias="partition")
