"""
Generated by qenerate plugin=pydantic_v1. DO NOT MODIFY MANUALLY!
"""
from typing import (  # noqa: F401 # pylint: disable=W0611
    Any,
    Callable,
    Optional,
    Union,
)

from pydantic import (  # noqa: F401 # pylint: disable=W0611
    BaseModel,
    Extra,
    Field,
    Json,
)

from reconcile.gql_definitions.change_owners.fragments.change_type import ChangeType


DEFINITION = """
fragment ChangeType on ChangeType_v1 {
  name
  contextType
  contextSchema
  changes {
    provider
    changeSchema
    context {
      selector
      when
    }
    ... on ChangeTypeChangeDetectorJsonPathProvider_v1 {
      jsonPathSelectors
    }
  }
}

query ChangeTypes {
  change_types: change_types_v1 {
    ... ChangeType
  }
}
"""


class ChangeTypesQueryData(BaseModel):
    change_types: Optional[list[Optional[ChangeType]]] = Field(
        ..., alias="change_types"
    )

    class Config:
        smart_union = True
        extra = Extra.forbid


def query(query_func: Callable, **kwargs) -> ChangeTypesQueryData:
    """
    This is a convenience function which queries and parses the data into
    concrete types. It should be compatible with most GQL clients.
    You do not have to use it to consume the generated data classes.
    Alternatively, you can also mime and alternate the behavior
    of this function in the caller.

    Parameters:
        query_func (Callable): Function which queries your GQL Server
        kwargs: optional arguments that will be passed to the query function

    Returns:
        ChangeTypesQueryData: queried data parsed into generated classes
    """
    raw_data: dict[Any, Any] = query_func(DEFINITION, kwargs)
    return ChangeTypesQueryData(**raw_data)
